version: "3.9"

services:
    instance1:
        container_name: instance1
        image: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "8081:3000"

    instance2:
        container_name: instance2
        image: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "8082:3000"